using System;
using System.Collections.Generic;
using System.Linq;

namespace AAEmu.Game.Models.Game.Items.Services
{
    public enum ItemCapabilityCoverageState
    {
        Unknown,
        Confirmed,
        Missing,
        Blocked,
        NotApplicable
    }

    public sealed class ItemCapabilityCoverage
    {
        public uint ItemId { get; set; }
        public string Dimension { get; set; } = string.Empty;
        public ItemCapabilityCoverageState State { get; set; }
        public string BlockerCode { get; set; } = string.Empty;
        public string Evidence { get; set; } = string.Empty;
    }

    /// <summary>
    /// Optional diagnostic catalogue generated by the AA8 item forensics tool.
    /// It never changes the creation gate in ItemDefinitionCoverageService.
    /// </summary>
    public sealed class ItemCapabilityCoverageService
    {
        private readonly Dictionary<uint, Dictionary<string, ItemCapabilityCoverage>>
            _coverage = new Dictionary<uint, Dictionary<string, ItemCapabilityCoverage>>();

        public static ItemCapabilityCoverageService Instance { get; } =
            new ItemCapabilityCoverageService();

        public bool CatalogueAvailable => _coverage.Count > 0;

        public void Clear()
        {
            _coverage.Clear();
        }

        public void Register(ItemCapabilityCoverage coverage)
        {
            if (coverage == null)
                throw new ArgumentNullException(nameof(coverage));
            if (string.IsNullOrWhiteSpace(coverage.Dimension))
                throw new ArgumentException(
                    "Capability coverage dimension is required.",
                    nameof(coverage));

            if (!_coverage.TryGetValue(coverage.ItemId, out var dimensions))
            {
                dimensions = new Dictionary<string, ItemCapabilityCoverage>(
                    StringComparer.OrdinalIgnoreCase);
                _coverage.Add(coverage.ItemId, dimensions);
            }

            dimensions[coverage.Dimension] = coverage;
        }

        public IReadOnlyList<ItemCapabilityCoverage> Get(uint itemId)
        {
            if (!_coverage.TryGetValue(itemId, out var dimensions))
                return Array.Empty<ItemCapabilityCoverage>();
            return dimensions.Values
                .OrderBy(value => value.Dimension, StringComparer.Ordinal)
                .ToList();
        }
    }
}
