namespace AAEmu.Game.Core.Packets.G2C;

public static class SCOffsets
{
    public const ushort X2EnterWorldResponsePacket = 0x000;
    public const ushort SCReconnectAuthPacket = 0x0F5;
    public const ushort SCPrepareLeaveWorldPacket = 0x0D1;
    public const ushort SCLeaveWorldGrantedPacket = 0x1FF;
    public const ushort SCLeaveWorldCanceledPacket = 0x14F;
    public const ushort SCWorldQueuePacket = 0x2CF;
    public const ushort SCInitialConfigPacket = 0x331;
    public const ushort SCTrionConfigPacket = 0x296;
    public const ushort SCFactionRelationListPacket = 0x226; // 10.0.2.13
    public const ushort SCExpeditionRolePolicyListPacket = 0x031; // 10.0.2.13
    public const ushort SCExpeditionRolePolicyChangedPacket = 0x227; // 10.0.2.13
    public const ushort SCExpeditionRoleChangedPacket = 0xfff; // 10.0.2.13
    public const ushort SCExpeditionOwnerChangedPacket = 0x075; // 10.0.2.13
    public const ushort SCExpeditionShowRenameUIPacket = 0xfff; // 10.0.2.13
    public const ushort SCNationShowRenameUIPacket = 0x10;
    public const ushort SCFactionRenamedPacket = 0x33B; // 10.0.2.13
    public const ushort SCFactionRetryRenamePacket = 0x1B9; // 10.0.2.13
    public const ushort SCFactionCreatedPacket = 0xfff;
    public const ushort SCExpeditionSponsorChangedPacket = 0x319; // 10.0.2.13
    public const ushort SCExpeditionDismissedPacket = 0x134; // 10.0.2.13
    public const ushort SCExpeditionMemberListPacket = 0x0C8; // 10.0.2.13
    public const ushort SCExpeditionMemberStatusChangedPacket = 0x02C; // 10.0.2.13
    public const ushort SCFactionOwnerChangedPacket = 0xfff;
    public const ushort SCFactionSetRelationStatePacket = 0xfff; // 10.0.2.13
    public const ushort SCExpeditionInvitationPacket = 0x324; // 10.0.2.13
    public const ushort SCUnitFactionChangedPacket = 0x366; // 10.0.2.13 (10.0.2.13 name: UnitFactionChangedPacket)
    public const ushort SCUnitExpeditionChangedPacket = 0x28A; // 10.0.2.13 (10.0.2.13 name: UnitExpeditionChangedPacket)
    public const ushort SCDominionDataPacket = 0x019; // 10.0.2.13
    public const ushort SCDominionDeletedPacket = 0x09F; // 10.0.2.13
    public const ushort SCDominionOwnerChangedPacket = 0x0C1; // 10.0.2.13
    public const ushort SCDominionTaxRatePacket = 0xfff; // 10.0.2.13
    public const ushort SCNationalTaxRatePacket = 0xfff;
    public const ushort SCNationalMonumentChangedPacket = 0xfff;
    public const ushort SCDominionTaxBalancedPacket = 0xfff;
    public const ushort CDominionStartUnkPacket = 0x24;
    public const ushort SCDominionEndUnkPacket = 0x25;
    public const ushort SCFactionIndependencePacket = 0xfff;
    public const ushort SCFactionImmigrateInvitePacket = 0xfff;
    public const ushort SCFactionImmigrateInviteResultPacket = 0xfff;
    public const ushort SCFactionImmigrateToOriginResultPacket = 0x26A;
    public const ushort SCFactionKickToOriginResultPacket = 0xfff;
    public const ushort SCFactionDeclareHostileResultPacket = 0xfff;
    public const ushort SCFactionRelationExpiredPacket = 0xfff;
    public const ushort SCFamilyInvitationPacket = 0x339; // 10.0.2.13
    public const ushort SCFamilyCreatedPacket = 0x0E2; // 10.0.2.13
    public const ushort SCFamilyRemovedPacket = 0x14E; // 10.0.2.13
    public const ushort SCFamilyDescPacket = 0x55; // 10.0.2.13
    public const ushort SCFamilyMemberAddedPacket = 0x35C; // 10.0.2.13
    public const ushort SCFamilyMemberRemovedPacket = 0x193; // 10.0.2.13
    public const ushort SCFamilyOwnerChangedPacket = 0x0FB; // 10.0.2.13
    public const ushort SCFamilyTitleChangedPacket = 0x2A1; // 10.0.2.13
    public const ushort SCFamilyMemberNameChangedPacket = 0x25E; // 10.0.2.13
    public const ushort SCFamilyTitlePacket = 0x23B; // 10.0.2.13
    public const ushort SCFamilyMemberOnlinePacket = 0x0B8; // 10.0.2.13
    public const ushort SCCreateCharacterResponsePacket = 0x2DD; // 10.0.2.13 (10.0.2.13 name: CreateCharacterResponsePacket)
    public const ushort SCDeleteCharacterResponsePacket = 0x64; // 10.0.2.13 (10.0.2.13 name: DeleteCharacterResponsePacket)
    public const ushort SCEditCharacterResponsePacket = 0x252; // 10.0.2.13
    public const ushort SCCharacterDeletedPacket = 0x36F; // 10.0.2.13
    public const ushort SCCancelCharacterDeleteResponsePacket = 0xfff; // 10.0.2.13 (10.0.2.13 name: CancelCharacterDeleteResponsePacket)
    public const ushort SCCharacterCreationFailedPacket = 0x194; // 10.0.2.13 (10.0.2.13 name: CharacterCreationFailedPacket)
    public const ushort SCCharacterListPacket = 0x170;
    public const ushort SCCheckRaceCongestionResponsePacket = 0x178;
    public const ushort SCRaceCongestionPacket = 0x173;
    public const ushort SCCharacterStatePacket = 0x369; // 10.0.2.13 (10.0.2.13 name: CharacterStatePacket)
    public const ushort SCNotifyResurrectionPacket = 0x12F; // 10.0.2.13
    public const ushort SCCharacterResurrectedPacket = 0x0F6; // 10.0.2.13 (10.0.2.13 name: CharacterResurrectedPacket)
    public const ushort SCForceAttackSetPacket = 0x34C; // 10.0.2.13
    public const ushort SCCharacterLaborPowerChangedPacket = 0x70; // 10.0.2.13
    public const ushort SCBmPointPacket = 0x0E8; // 10.0.2.13
    public const ushort SCAddActionPointPacket = 0xfff; // 10.0.2.13
    public const ushort SCLpManagedPacket = 0xfff; // 10.0.2.13
    public const ushort SCCharacterBoundPacket = 0x34E; // 10.0.2.13
    public const ushort SCCooldownsPacket = 0x34D; // 10.0.2.13
    public const ushort SCCharacterInvenInitPacket = 0x26B; // 10.0.2.13
    public const ushort SCCharacterInvenContentsPacket = 0x27B; // 10.0.2.13
    public const ushort SCInvenExpandedPacket = 0x78; // 10.0.2.13
    public const ushort SCFriendsPacket = 0xfff; // 10.0.2.13
    public const ushort SCSearchListPacket = 0xfff; // 10.0.2.13
    public const ushort SCDeleteFriendPacket = 0x01E; // 10.0.2.13
    public const ushort SCFriendStatusChangedPacket = 0x027; // 10.0.2.13
    public const ushort SCCharDetailPacket = 0x2E2; // 10.0.2.13
    public const ushort SCBlockedUsersPacket = 0x33E; // 10.0.2.13
    public const ushort SCAddBlockedUserPacket = 0x04D; // 10.0.2.13
    public const ushort SCDeleteBlockedUserPacket = 0x103; // 10.0.2.13
    public const ushort SCLoginCharInfoHousePacket = 0xfff;
    public const ushort SCCharBriefPacket = 0xfff; // 10.0.2.13
    public const ushort SCPlaytimePacket = 0xfff;  // 10.0.2.13
    public const ushort SCCharacterRenamedPacket = 0x2C3; // 10.0.2.13
    // Portals=136, ReturnDistricts=137, PortalInfoSaved=138, PortalDeleted=139.
    // The old 0x5b/0x5c values collided with SCFamilyTitle / SCFamilyMemberOnline,
    // so discovered districts never reached the client's book UI.
    public const ushort SCCharacterPortalsPacket = 0x1FA; // 10.0.2.13
    public const ushort SCCharacterReturnDistrictsPacket = 0x2BA; // 10.0.2.13
    public const ushort SCPortalInfoSavedPacket = 0xfff; // 10.0.2.13
    public const ushort SCPortalDeletedPacket = 0x09C; // 10.0.2.13
    public const ushort SCUnitPortalUsedPacket = 0x273; // 10.0.2.13
    public const ushort SCSlaveCreatedPacket = 0x14B; // 10.0.2.13
    public const ushort SCSlaveRemovedPacket = 0x0F0; // 10.0.2.13
    public const ushort SCSlaveDespawnPacket = 0x348; // 10.0.2.13
    public const ushort SCSlaveBoundPacket = 0x2B6; // 10.0.2.13
    public const ushort SCQuestListPacket = 0x195; // 10.0.2.13
    public const ushort SCMySlavePacket = 0x2D0; // 10.0.2.13
    public const ushort SCEscapeSlavePacket = 0xfff; // 10.0.2.13
    public const ushort SCSlaveEquipmentChangedPacket = 0x224; // 10.0.2.13
    public const ushort SCUnitStatePacket = 0x15C; // 10.0.2.13 (10.0.2.13 name: UnitStatePacket)
    public const ushort SCUnitsRemovedPacket = 0x230; // 10.0.2.13
    public const ushort SCUnitMovementsPacket = 0x1FB; // 10.0.2.13
    public const ushort SCOneUnitMovementPacket = 0x349; // 10.0.2.13
    public const ushort SCSkillControllerStatePacket = 0x10D; // 10.0.2.13
    public const ushort SCUnitOfflinePacket = 0x9E; // 10.0.2.13
    public const ushort SCActiveWeaponChangedPacket = 0x1D4; // 10.0.2.13
    public const ushort SCUnitNameChangedPacket = 0x206; // 10.0.2.13
    public const ushort SCUnitDeathPacket = 0x1A8; // 10.0.2.13 (10.0.2.13 name: UnitDeathPacket)
    public const ushort SCTeleportUnitPacket = 0xA2; // 10.0.2.13
    public const ushort SCBlinkUnitPacket = 0xfff; // 10.0.2.13
    public const ushort SCKnockBackUnitPacket = 0xfff; // 10.0.2.13
    public const ushort SCUnitAttachedPacket = 0x1DC; // 10.0.2.13 (10.0.2.13 name: UnitAttachedPacket)
    public const ushort SCUnitDetachedPacket = 0x043; // 10.0.2.13 (10.0.2.13 name: UnitDetachedPacket)
    public const ushort SCUnitInvisiblePacket = 0x1ED; // 10.0.2.13
    public const ushort SCUnitImpulsePacket = 0xA8; // 10.0.2.13
    public const ushort SCUnitFlyingStateChangedPacket = 0x31B; // 10.0.2.13
    public const ushort SCNpcInteractionSkillListPacket = 0x1BD; // 10.0.2.13
    public const ushort SCNpcInteractionEndedByZonePacket = 0x2BB; // 10.0.2.13
    public const ushort SCWorldInteractionSkillListPacket = 0x24C; // 10.0.2.13
    public const ushort SCWorldInteractionCanceledPacket = 0xAD; // 10.0.2.13
    public const ushort SCNpcInteractionStatusChangedPacket = 0xAE; // 10.0.2.13
    public const ushort SCVegetationCutdowningPacket = 0x0E4; // 10.0.2.13
    public const ushort SCNpcFriendshipListPacket = 0x82;
    public const ushort SCNpcFriendshipChangedPacket = 0x83;
    public const ushort SCTargetChangedPacket = 0x196; // 10.0.2.13 (10.0.2.13 name: TargetChangedPacket)
    public const ushort SCCombatEngagedPacket = 0x363; // 10.0.2.13
    public const ushort SCCombatClearedPacket = 0x0D8; // 10.0.2.13
    public const ushort SCCvFCombatRelationshipPacket = 0xfff; // 10.0.2.13
    public const ushort SCFvFCombatRelationshipPacket = 0x307; // 10.0.2.13
    public const ushort SCCombatFirstHitPacket = 0x1CA; // 10.0.2.13
    public const ushort SCDumpCombatStatPacket = 0x27F;  // 10.0.2.13
    public const ushort SCDuelChallengedPacket = 0x23A; // 10.0.2.13
    public const ushort SCDuelStartCountdownPacket = 0x305; // 10.0.2.13
    public const ushort SCDuelStartedPacket = 0x247; // 10.0.2.13
    public const ushort SCDuelEndedPacket = 0x01C; // 10.0.2.13
    public const ushort SCDuelStatePacket = 0x0E1; // 10.0.2.13
    public const ushort SCItemTaskSuccessPacket = 0x054; // 10.0.2.13
    public const ushort SCItemTaskNotifyPacket = 0x2AE; // 10.0.2.13
    public const ushort SCItemDetailUpdatedPacket = 0x320; // 10.0.2.13
    public const ushort SCUnitEquipmentsChangedPacket = 0x01F; // 10.0.2.13
    public const ushort SCUnitEquipmentIdsPacket = 0x014; // 10.0.2.13
    public const ushort SCCofferContentsUpdatePacket = 0xC2; // 10.0.2.13
    public const ushort SCItemAcquisitionPacket = 0x229; // 10.0.2.13
    public const ushort SCSyncItemLifespanPacket = 0x0B5; // 10.0.2.13
    public const ushort SCSpecialtyRatioPacket = 0xfff; // 10.0.2.13
    public const ushort SCSpecialtyGoodsPacket = 0xC6; // 10.0.2.13
    public const ushort SCSpecialtyRecordsPacket = 0x1FE; // 10.0.2.13
    public const ushort SCGradeEnchantResultPacket = 0xfff; // 10.0.2.13
    public const ushort SCItemSocketingLunagemResultPacket = 0x9d;
    public const ushort SCItemSocketingLunastoneResultPacket = 0x9e;
    public const ushort SCGradeEnchantBroadcastPacket = 0xfff; // 10.0.2.13
    public const ushort SCUnknownPacket = 0xa0;
    public const ushort SCSkillStartedPacket = 0x2F9; // 10.0.2.13 (10.0.2.13 name: SkillStartedPacket)
    public const ushort SCSkillFiredPacket = 0x2D9; // 10.0.2.13 (10.0.2.13 name: SkillFiredPacket)
    public const ushort SCSkillEndedPacket = 0x345; // 10.0.2.13 (10.0.2.13 name: SkillEndedPacket)
    public const ushort SCSkillStoppedPacket = 0x1B6; // 10.0.2.13 (10.0.2.13 name: SkillStoppedPacket)
    public const ushort SCCastingStoppedPacket = 0x0C0; // 10.0.2.13
    public const ushort SCCastingDelayedPacket = 0x1A7; // 10.0.2.13
    public const ushort SCUnitDamagedPacket = 0x039; // 10.0.2.13 (10.0.2.13 name: UnitDamagedPacket)
    public const ushort SCUnitHealedPacket = 0x2BF; // 10.0.2.13 (10.0.2.13 name: UnitHealedPacket)
    public const ushort SCUnitTrackedPacket = 0x354; // 10.0.2.13
    public const ushort SCBombUpdatedPacket = 0x057; // 10.0.2.13
    public const ushort SCCombatTextPacket = 0x355; // 10.0.2.13
    public const ushort SCSkillCooldownResetPacket = 0x098; // 10.0.2.13
    public const ushort SCPlotEventPacket = 0x0D5;  // 10.0.2.13
    public const ushort SCPlotEndedPacket = 0x072; // 10.0.2.13
    public const ushort SCPlotProcessingTimePacket = 0x071;  // 10.0.2.13
    public const ushort SCPlotCastingStoppedPacket = 0x253; // 10.0.2.13
    public const ushort SCPlotChannelingStoppedPacket = 0x088; // 10.0.2.13
    public const ushort SCEnvDamagePacket = 0x05C; // 10.0.2.13
    public const ushort SCOnOffSnowPacket = 0xfff;
    public const ushort SCUnkPacket = 0xb5;
    public const ushort SCBuffCreatedPacket = 0x36C; // 10.0.2.13
    public const ushort SCBuffRemovedPacket = 0x023; // 10.0.2.13
    public const ushort SCBuffUpdatedPacket = 0x1DE; // 10.0.2.13
    public const ushort SCUnitPointsPacket = 0x327; // 10.0.2.13
    public const ushort SCUnitBountyMoneyPacket = 0xfff;
    public const ushort SCHouseStatePacket = 0x1C1; // 10.0.2.13
    public const ushort SCHouseBuildProgressPacket = 0x1C3; // 10.0.2.13
    public const ushort SCHousePermissionChangedPacket = 0x2CB; // 10.0.2.13
    public const ushort SCHouseBuildPayChangedPacket = 0xfff;
    public const ushort SCHouseDemolishedPacket = 0x24E; // 10.0.2.13
    public const ushort SCHouseDataPacket = 0xF4; // 10.0.2.13
    public const ushort SCHouseRemovedPacket = 0x35E; // 10.0.2.13
    public const ushort SCHouseFarmPacket = 0x1B7; // 10.0.2.13
    public const ushort SCHouseTaxInfoPacket = 0x1D3; // 10.0.2.13
    public const ushort SCConstructHouseTaxPacket = 0x092; // 10.0.2.13
    public const ushort SCHousingRecoverTogglePacket = 0xfff; // 10.0.2.13
    public const ushort SCHouseSetForSalePacket = 0x2C9; // 10.0.2.13
    public const ushort SCHouseResetForSalePacket = 0x2B9; // 10.0.2.13
    public const ushort SCHouseSoldPacket = 0x1F1; // 10.0.2.13
    public const ushort SCHouseOwnerNameChangedPacket = 0x230; // 10.0.2.13
    public const ushort SCJoinedChatChannelPacket = 0x217; // 10.0.2.13
    public const ushort SCLeavedChatChannelPacket = 0x259; // 10.0.2.13
    public const ushort SCChatMessagePacket = 0x2F6; // 10.0.2.13
    public const ushort SCNpcChatMessagePacket = 0x282; // 10.0.2.13
    public const ushort SCNoticeMessagePacket = 0x213; // 10.0.2.13
    public const ushort SCChatFailedPacket = 0x1B3; // 10.0.2.13
    public const ushort SCChatLocalizedMessagePacket = 0x2C4; // 10.0.2.13
    public const ushort SCChatSpamDelayPacket = 0x107; // 10.0.2.13 SCChatSpamConfig (1.2 was 0xd3)
    public const ushort SCAskToJoinTeamPacket = 0x0AF; // 10.0.2.13
    public const ushort SCAskToJoinTeamAreaPacket = 0x02E; // 10.0.2.13
    public const ushort SCJoinedTeamPacket = 0x19C;
    public const ushort SCRejectedTeamPacket = 0x04F; // 10.0.2.13
    public const ushort SCLeavedTeamPacket = 0x2B5; // 10.0.2.13
    public const ushort SCTeamDismissedPacket = 0x182; // 10.0.2.13
    public const ushort SCTeamMemberJoinedPacket = 0x2E6; // 10.0.2.13
    public const ushort SCTeamMemberLeavedPacket = 0x114; // 10.0.2.13
    public const ushort SCTeamMemberDisconnectedPacket = 0xfff; // 10.0.2.13
    public const ushort SCTeamOwnerChangedPacket = 0x180; // 10.0.2.13
    public const ushort SCTeamMemberRoleChangedPacket = 0xfff; // 10.0.2.13
    public const ushort SCTeamBecameRaidTeamPacket = 0xfff; // 10.0.2.13
    public const ushort SCTeamMemberMovedPacket = 0x2D8; // 10.0.2.13
    public const ushort SCTeamLootingRuleChangedPacket = 0x2A9; // 10.0.2.13
    public const ushort SCRefreshTeamMemberPacket = 0x2D4; // 10.0.2.13
    public const ushort SCTeamRemoteMembersExPacket = 0x12B; // 10.0.2.13
    public const ushort SCTeamAreaInvitedPacket = 0x026; // 10.0.2.13
    public const ushort SCOverHeadMarkerSetPacket = 0x05D; // 10.0.2.13
    public const ushort SCTeamPingPosPacket = 0x33C; // 10.0.2.13
    public const ushort SCTeamAckRiskyActionPacket = 0x0FA; // 10.0.2.13
    public const ushort SCTeamAskHandOverOwnerPacket = 0x0D4; // 10.0.2.13
    public const ushort SCTeamAskAcceptOwnerOfferPacket = 0x16B; // 10.0.2.13
    public const ushort SCTeamHandOverOwnerOfferResultPacket = 0x347; // 10.0.2.13
    public const ushort SCSiegeStatePacket = 0x1CB; // 10.0.2.13
    public const ushort SCSiegeDeclaredPacket = 0x32E; // 10.0.2.13
    public const ushort SCSiegeReinforcePacket = 0xeb;
    public const ushort SCSiegeMemberPacket = 0x139; // 10.0.2.13
    public const ushort SCSiegeAlertPacket = 0x133; // 10.0.2.13
    public const ushort SCConflictZoneStatePacket = 0x30A; // 10.0.2.13
    public const ushort SCConflictZoneHonorPointSumPacket = 0x0C7; // 10.0.2.13
    public const ushort SCTimeOfDayPacket = 0x130; // 10.0.2.13 (10.0.2.13 name: TimeOfDayPacket)
    public const ushort SCDetailedTimeOfDayPacket = 0x131; // 10.0.2.13 (10.0.2.13 name: DetailedTimeOfDayPacket)
    public const ushort SCQuestsPacket = 0x1B4; // 10.0.2.13 SC_PACKET_QUESTS (306)
    public const ushort SCCompletedQuestsPacket = 0x081; // 10.0.2.13
    public const ushort SCCraftItemUnlockPacket = 0x134; // 10.0.2.13
    public const ushort SCLootableStatePacket = 0x367; // 10.0.2.13
    public const ushort SCUnitLootingStatePacket = 0x284; // 10.0.2.13
    public const ushort SCLootBagDataPacket = 0x192; // 10.0.2.13
    public const ushort SCLootItemTookPacket = 0x1F4; // 10.0.2.13
    public const ushort SCLootItemFailedPacket = 0x233; // 10.0.2.13
    public const ushort SCLootDicePacket = 0x0C4; // 10.0.2.13
    public const ushort SCLootDiceNotifyPacket = 0x1A9; // 10.0.2.13
    public const ushort SCLootDiceSummaryPacket = 0x1FD; // 10.0.2.13
    public const ushort SCExpChangedPacket = 0x1C4; // 10.0.2.13
    public const ushort SCAbilityExpChangedPacket = 0x211; // 10.0.2.13
    public const ushort SCRecoverableExpPacket = 0x2DE; // 10.0.2.13
    public const ushort SCMileageChangedPacket = 0xfff;
    public const ushort SCLevelChangedPacket = 0x0BC; // 10.0.2.13
    public const ushort SCUnitModelPostureChangedPacket = 0x2B0; // 10.0.2.13 (10.0.2.13 name: UnitModelPostureChangedPacket)
    public const ushort SCSkillLearnedPacket = 0x162; // 10.0.2.13
    public const ushort SCSkillUpgradedPacket = 0xfff;
    public const ushort SCBuffLearnedPacket = 0x1F3; // 10.0.2.13
    public const ushort SCSkillsResetPacket = 0x1AB; // 10.0.2.13
    public const ushort SCAbilitySwappedPacket = 0x175; // 10.0.2.13
    public const ushort SCErrorMsgPacket = 0x272; // 10.0.2.13 (10.0.2.13 name: ErrorMsgPacket)
    public const ushort SCDoodadCreatedPacket = 0x2E8; // 10.0.2.13 (10.0.2.13 name: DoodadCreatedPacket)
    public const ushort SCDoodadRemovedPacket = 0x031; // 10.0.2.13 (10.0.2.13 name: DoodadRemovedPacket)
    public const ushort SCDoodadChangedPacket = 0x306; // 10.0.2.13 (10.0.2.13 name: DoodadChangedPacket)
    public const ushort SCDoodadPhaseChangedPacket = 0x0CF; // 10.0.2.13
    public const ushort SCDoodadPuzzleScenePacket = 0x002; // 10.0.2.13
    public const ushort SCDoodadQuestAcceptPacket = 0xfff; // 10.0.2.13
    public const ushort SCDoodadsCreatedPacket = 0x056; // 10.0.2.13
    public const ushort SCDoodadsRemovedPacket = 0x155; // 10.0.2.13
    public const ushort SCDoodadOriginatorPacket = 0x1AA; // 10.0.2.13
    public const ushort SCMailFailedPacket = 0x15A; // 10.0.2.13
    public const ushort SCMailSentPacket = 0x2D2; // 10.0.2.13
    public const ushort SCGotMailPacket = 0x050; // 10.0.2.13
    public const ushort SCCountTotalMailPacket = 0x15B; // 10.0.2.13
    public const ushort SCMailListPacket = 0x33D; // 10.0.2.13
    public const ushort SCMailListEndPacket = 0x1D1; // 10.0.2.13
    public const ushort SCMailBodyPacket = 0x12A; // 10.0.2.13
    public const ushort SCMailReceiverOpenedPacket = 0x0E9; // 10.0.2.13
    public const ushort SCAttachmentTakenPacket = 0xfff; // 10.0.2.13
    public const ushort SCChargeMoneyPaidPacket = 0x1AF; // 10.0.2.13
    public const ushort SCMailDeletedPacket = 0x0A8; // 10.0.2.13
    public const ushort SCSpamReportedPacket = 0x0FE;
    public const ushort SCMailReturnedPacket = 0x035; // 10.0.2.13
    public const ushort SCMailStatusUpdatedPacket = 0x166; // 10.0.2.13
    public const ushort SCMailRemovedPacket = 0x191; // 10.0.2.13
    public const ushort SCMineAmountPacket = 0xfff;  // 10.0.2.13
    public const ushort SCMateSpawnedPacket = 0x195; // 10.0.2.13
    public const ushort SCMateEquipmentChangedPacket = 0x338; // 10.0.2.13
    public const ushort SCMateEquipmentExpiredPacket = 0x210; // 10.0.2.13
    public const ushort SCUnkPacket4 = 0x128;
    public const ushort SCEmotionExpressedPacket = 0x30B; // 10.0.2.13
    public const ushort SCSoldItemListPacket = 0x2EF; // 10.0.2.13
    public const ushort SCActionSlotsPacket = 0x144; // 10.0.2.13
    public const ushort SCAuctionPostedPacket = 0xfff; // 10.0.2.13
    public const ushort SCAuctionSearchedPacket = 0xfff; // 10.0.2.13
    public const ushort SCAuctionLowestPricePacket = 0xfff; // 10.0.2.13
    public const ushort SCAuctionBidPacket = 0x228; // 10.0.2.13
    public const ushort SCAuctionCanceledPacket = 0xfff; // 10.0.2.13
    public const ushort SCAuctionMessagePacket = 0xfff; // 10.0.2.13
    public const ushort SCDiceValuePacket = 0x013; // 10.0.2.13
    public const ushort SCDiceBidRuleChangedPacket = 0x17A; // 10.0.2.13
    public const ushort SCNpcSpawnerPacket = 0x135;
    public const ushort SCActabilityPacket = 0x2D7; // 10.0.2.13
    public const ushort SCHungPacket = 0x1B1; // 10.0.2.13
    public const ushort SCUnhungPacket = 0x248; // 10.0.2.13
    public const ushort SCBondDoodadPacket = 0x275; // 10.0.2.13
    public const ushort SCUnbondDoodadPacket = 0x352; // 10.0.2.13
    public const ushort SCPlaySequencePacket = 0x0DA; // 10.0.2.13
    // (112-byte stride) places SCGimmicksCreatedPacket between SCPlaySequencePacket (0x180) and
    // SCGimmicksRemovedPacket (0x182).
    public const ushort SCGimmicksCreatedPacket = 0x30C; // 10.0.2.13
    public const ushort SCGimmicksRemovedPacket = 0x04B; // 10.0.2.13
    public const ushort SCGimmickMovementPacket = 0x0DE; // 10.0.2.13
    public const ushort SCGimmickJointsBrokenPacket = 0x223; // 10.0.2.13
    public const ushort SCGimmickResetJointsPacket = 0x107; // 10.0.2.13
    public const ushort SCGimmickGraspedPacket = 0x022; // 10.0.2.13
    public const ushort SCWorldRayCastingResultPacket = 0x28D; // 10.0.2.13
    public const ushort SCWorldAimPointPacket = 0x059;  // 10.0.2.13
    public const ushort SCWorldAABBPacket = 0x189;  // 10.0.2.13
    public const ushort SCUnkPacket5 = 0x145;
    public const ushort SCQuestContextFailedPacket = 0x2CC; // 10.0.2.13
    public const ushort SCQuestContextStartedPacket = 0x35D; // 10.0.2.13
    public const ushort SCQuestUnitReqFailedPacket = 0x19F; // 10.0.2.13
    public const ushort SCQuestContextUpdatedPacket = 0x051; // 10.0.2.13
    public const ushort CSQuestAcceptConditionalPacket = 0x14a;
    public const ushort SCQuestContextCompletedPacket = 0x20D; // 10.0.2.13
    public const ushort SCQuestContextResetPacket = 0x0F4; // 10.0.2.13
    public const ushort SCDoodadCompleteQuestPacket = 0x0AD; // 10.0.2.13
    public const ushort SCQuestRewardedByMailPacket = 0x194; // 10.0.2.13
    public const ushort SCQuestMailSentPacket = 0x220; // 10.0.2.13
    public const ushort SCScheduleItemSentPacket = 0x197; // 10.0.2.13
    public const ushort SCSoundAreaEventPacket = 0x2A0; // 10.0.2.13
    public const ushort SCAreaChatBubblePacket = 0x1A2; // 10.0.2.13
    public const ushort SCChatBubblePacket = 0x243; // 10.0.2.13
    public const ushort SCAreaTeamMessagePacket = 0x157; // 10.0.2.13
    public const ushort SCDoodadSoundPacket = 0x187; // 10.0.2.13
    public const ushort SCDoodadPhaseMsgPacket = 0x073; // 10.0.2.13
    public const ushort SCDoodadUccStringPacket = 0x1A0; // 10.0.2.13
    public const ushort SCDoodadUccDataPacket = 0x02F; // 10.0.2.13
    public const ushort SCUccCharacterNameLoadedPacket = 0x1A2; // 10.0.2.13
    public const ushort SCNaviTeleportPacket = 0x2F1; // 10.0.2.13
    public const ushort SCItemUccDataChangedPacket = 0xfff; // 10.0.2.13
    public const ushort SCCanStartTradePacket = 0x10A; // 10.0.2.13
    public const ushort SCCannotStartTradePacket = 0x2EC; // 10.0.2.13
    public const ushort SCTradeStartedPacket = 0x2B2; // 10.0.2.13
    public const ushort SCTradeCanceledPacket = 0x2CE; // 10.0.2.13
    public const ushort SCTradeItemPutupPacket = 0x137; // 10.0.2.13
    public const ushort SCOtherTradeItemPutupPacket = 0x1DD; // 10.0.2.13
    public const ushort SCTradeMoneyPutupPacket = 0x14C; // 10.0.2.13
    public const ushort SCOtherTradeMoneyPutupPacket = 0x0CE; // 10.0.2.13
    public const ushort SCTradeItemTookdownPacket = 0x105; // 10.0.2.13
    public const ushort SCOtherTradeItemTookdownPacket = 0x041; // 10.0.2.13
    public const ushort SCTradeOkUpdatePacket = 0xfff; // 10.0.2.13
    public const ushort SCTradeLockUpdatePacket = 0x199; // 10.0.2.13
    public const ushort SCTradeMadePacket = 0x1E9; // 10.0.2.13
    public const ushort SCTowerDefListPacket = 0x119;  // 10.0.2.13
    public const ushort SCTowerDefStartPacket = 0x351; // 10.0.2.13
    public const ushort SCTowerDefEndPacket = 0x0BA; // 10.0.2.13
    public const ushort SCTowerDefWaveStartPacket = 0x207; // 10.0.2.13
    public const ushort SCCrimeChangedPacket = 0x1B6; // 10.0.2.13
    public const ushort SCCriminalArrestedPacket = 0x22D; // 10.0.2.13
    public const ushort SCAskImprisonOrTrialPacket = 0x346; // 10.0.2.13
    public const ushort SCInviteJuryPacket = 0x151; // 10.0.2.13
    public const ushort SCSummonJuryPacket = 0x01B; // 10.0.2.13
    public const ushort SCJuryBeSeatedPacket = 0x0BD; // 10.0.2.13
    public const ushort SCSummonDefendantPacket = 0x2D6; // 10.0.2.13
    public const ushort SCCrimeDataPacket = 0x1C0; // 10.0.2.13
    public const ushort SCCrimeRecordsPacket = 0x006; // 10.0.2.13
    public const ushort SCChangeTrialStatePacket = 0x2F0; // 10.0.2.13
    public const ushort SCChangeJuryOKCountPacket = 0xfff; // 10.0.2.13
    public const ushort SCChangeJuryVerdictCountPacket = 0xfff; // 10.0.2.13
    public const ushort SCTrialWaitStatusPacket = 0x2AB; // 10.0.2.13
    public const ushort SCJuryWaitStatusPacket = 0x25C; // 10.0.2.13
    public const ushort SCRulingStatusPacket = 0x0CA; // 10.0.2.13
    public const ushort SCRulingClosedPacket = 0x122; // 10.0.2.13
    public const ushort SCTrialAudienceJoinedPacket = 0xfff; // 10.0.2.13
    public const ushort SCTrialAudienceLeftPacket = 0xfff; // 10.0.2.13
    public const ushort SCTrialInfoPacket = 0x2C6; // 10.0.2.13
    public const ushort SCJuryWaitingNumberPacket = 0x132; // 10.0.2.13
    public const ushort SCTrialCancledPacket = 0xfff; // 10.0.2.13
    public const ushort SCBotSuspectReportedPacket = 0x184;
    public const ushort SCBotSuspectArrestedPacket = 0x2DB; // 10.0.2.13
    public const ushort SCSuspectGoingBotTrial = 0x186;
    public const ushort SCUnderWaterPacket = 0x35F; // 10.0.2.13
    public const ushort SCCharacterGamePointsPacket = 0xfff; // 10.0.2.13
    public const ushort SCGamePointChangedPacket = 0x07A; // 10.0.2.13
    public const ushort SCJuryPointChangedPacket = 0x263; // 10.0.2.13
    public const ushort SCAppliedToInstantGamePacket = 0x143; // 10.0.2.13
    public const ushort SCCancelInstantGamePacket = 0x276; // 10.0.2.13
    public const ushort SCInstantGameStatePacket = 0x18d;
    public const ushort SCInviteToInstantGamePacket = 0x1A4; // 10.0.2.13
    public const ushort SCInstantGameInviteTimeoutPacket = 0x18f;
    public const ushort SCInstantGameJoinedPacket = 0x21C; // 10.0.2.13
    public const ushort SCInstantGameStartPacket = 0x03E; // 10.0.2.13
    public const ushort SCInstantGameEndPacket = 0x2DA; // 10.0.2.13
    public const ushort SCInstantGameAddPointPacket = 0x193;
    public const ushort SCInstantGameKillPacket = 0x359; // 10.0.2.13
    public const ushort SCInstantGameKillstreakPacket = 0x28E; // 10.0.2.13
    public const ushort SCInstantGameUnkPacket = 0x196;
    public const ushort SCLoadInstancePacket = 0x149; // 10.0.2.13
    public const ushort SCProcessingInstancePacket = 0x125; // 10.0.2.13
    public const ushort SCGmCommandPacket = 0x2A8;  // 10.0.2.13
    public const ushort SCGmDumpInventoryPacket = 0x13E; // 10.0.2.13
    public const ushort SCGmDumpEquipmentPacket = 0x1F1; // 10.0.2.13
    public const ushort SCGmDumpQuestsPacket = 0x13D;
    public const ushort SCGmDumpCompletedQuestsPacket = 0x1E1;  // 10.0.2.13
    public const ushort SCGmDumpNpcPacket = 0x232;  // 10.0.2.13
    public const ushort SCUnkPacket8 = 0x19f;
    public const ushort SCKickedPacket = 0x07E; // 10.0.2.13
    public const ushort SCAccountWarnedPacket = 0x15A; // 10.0.2.13
    public const ushort SCAboxTeleportPacket = 0x20A; // 10.0.2.13
    public const ushort SCDelayedTaskOnInGameNotifyPacket = 0x20D; // 10.0.2.13
    public const ushort SCAppellationsPacket = 0x1E3; // 10.0.2.13
    public const ushort SCAppellationGainedPacket = 0x044; // 10.0.2.13
    public const ushort SCAppellationChangedPacket = 0x147; // 10.0.2.13
    public const ushort SCTutorialSavedPacket = 0x217; // 10.0.2.13
    public const ushort SCEmblemUploadedPacket = 0x293; // 10.0.2.13
    public const ushort SCEmblemDownloadedPacket = 0x219; // 10.0.2.13
    public const ushort SCShipyardStatePacket = 0x0D0; // 10.0.2.13
    public const ushort SCSlaveStatePacket = 0x01D; // 10.0.2.13
    public const ushort SCMateStatePacket = 0x07F; // 10.0.2.13
    public const ushort SCDumpCombatInfoPacket = 0x21D;  // 10.0.2.13
    public const ushort SCUccCheckecPacket = 0x21E; // 10.0.2.13
    public const ushort SCShowQuestAreaPacket = 0x11C; // 10.0.2.13
    public const ushort SCShowCommonFarmPacket = 0x220; // 10.0.2.13
    public const ushort SCResponseCommonFarmListPacket = 0xfff; // 10.0.2.13
    public const ushort SCTelescopeToggledPacket = 0x222; // 10.0.2.13
    public const ushort SCTelescopeUnitsPacket = 0x24A; // 10.0.2.13
    public const ushort SCTransferTelescopeToggledPacket = 0xfff; // 10.0.2.13
    public const ushort SCTransferTelescopeUnitsPacket = 0x159; // 10.0.2.13
    public const ushort SCSchoolOfFishFinderToggledPacket = 0x228; // 10.0.2.13
    public const ushort SCSchoolOfFishDoodadsPacket = 0x229; // 10.0.2.13
    public const ushort SCShowDemoModeUiPacket = 0x1b8;
    public const ushort SCDemoCharResetItemPacket = 0x1b9;
    public const ushort SCDemoCharResetLocPacket = 0x1ba;
    public const ushort SCDemoResetActionSlotPacket = 0x1bb;
    public const ushort SCSetBreathPacket = 0x034; // 10.0.2.13
    public const ushort SCDoodadReqBattleFieldPacket = 0x1be;
    public const ushort SCCraftFailedPacket = 0x1BC; // 10.0.2.13
    public const ushort SCExpertLimitModifiedPacket = 0x012; // 10.0.2.13
    public const ushort SCExpertExpandedPacket = 0x317; // 10.0.2.13
    public const ushort SCAccountInfoPacket = 0x00B;
    public const ushort SCAiDebugPacket = 0x1c3;
    public const ushort SCAiAggroPacket = 0xfff; // 10.0.2.13
    public const ushort SCHSRequestPacket = 0x1c5;
    public const ushort SCHackGuardRetAddrsRequestPacket = 0x1c6;
    public const ushort SCUnitLocationPacket = 0x0BF; // 10.0.2.13
    public const ushort SCRestrictInfoPacket = 0x1c8;
    public const ushort SCIsUnitInFarmPacket = 0x16F; // 10.0.2.13
    public const ushort SCResponseUIDataPacket = 0x2E4; // 10.0.2.13
    public const ushort SCUnitVisualOptionsPacket = 0x27A; // 10.0.2.13
    public const ushort SCNotifyUIMessagePacket = 0x249; // 10.0.2.13
    public const ushort SCResultRestrictCheckPacket = 0x0EF;
    public const ushort SCICSMenuListPacket = 0xfff;
    public const ushort SCICSGoodListPacket = 0x1d0;
    public const ushort SCICSGoodDetailPacket = 0x1d1;
    public const ushort SCICSCheckTimePacket = 0xfff;
    public const ushort SCICSBuyResultPacket = 0xfff;
    public const ushort SCICSSyncGoodPacket = 0xfff;
    public const ushort SCICSCashPointPacket = 0xfff;
    public const ushort SCICSExchangeRatioPacket = 0xfff;
    public const ushort SCPremiumServiceListPacket = 0x264; // 10.0.2.13
    public const ushort SCBountyListPacket = 0x1d9;
    public const ushort SCSetBountyPermittedPacket = 0x1da;
    public const ushort SCSetBountyDonePacket = 0x1db;
    public const ushort SCBountyPaidPacket = 0x1dc;
    public const ushort SCInvitationCanceledPacket = 0x003; // 10.0.2.13
    public const ushort SCPlaySoundPacket = 0x1B0; // 10.0.2.13
    public const ushort SCSendUserMusicPacket = 0x257; // 10.0.2.13
    public const ushort SCUserNoteLoadedPacket = 0x25A; // 10.0.2.13
    public const ushort SCPauseUserMusicPacket = 0x337; // 10.0.2.13
    public const ushort SCGetSlotCountPacket = 0x011;
    public const ushort SCSecondPassSettedPacket = 0x186; // 10.0.2.13
    public const ushort SCSecondPassKeyTablesPacket = 0x1D7; // 10.0.2.13
    public const ushort SCSecondPassChangedPacket = 0x060; // 10.0.2.13
    public const ushort SCSecondPassCheckedPacket = 0x087; // 10.0.2.13
    public const ushort SCSecondPassClearedPacket = 0x323; // 10.0.2.13
    public const ushort SCSecondPassCheckOverFailedPacket = 0x332; // 10.0.2.13
    public const ushort SCSecondPassAccountLockedPacket = 0x25A; // 10.0.2.13
    public const ushort SCSecondPassCreatedPacket = 0x314; // 10.0.2.13
    public const ushort SCScheduleItemUpdatePacket = 0xfff; // 10.0.2.13
    public const ushort SCScheduledEventStartedPacket = 0x26F; // 10.0.2.13
    public const ushort SCScheduledEventEndedPacket = 0x270; // 10.0.2.13
    public const ushort SCMouldListPacket = 0x1ee;
    public const ushort SCMouldAskedPacket = 0x1ef;
    public const ushort SCMouldTakenPacket = 0x1f0;
    public const ushort SCToggleBeautyshopResponsePacket = 0xfff; // 10.0.2.13
    public const ushort SCCharacterGenderAndModelModifiedPacket = 0x0CB; // 10.0.2.13
    public const ushort SCSpecialtyCurrentPacket = 0x32A; // 10.0.2.13
    public const ushort SCUnitIdleStatusPacket = 0x089; // 10.0.2.13
    public const ushort SCRaceCondPacket = 0x1f6;
    public const ushort SCRacingPacket = 0x1f7;
    public const ushort SCRacingResultPacket = 0x1f8;
    public const ushort SCRankRewardMailPacket = 0x27D; // 10.0.2.13
    public const ushort SCRankCharacterPacket = 0x1fa; // 10.0.2.13
    public const ushort SCAchievementsPacket = 0x0B9; // 10.0.2.13
    public const ushort SCAchievementChangedPacket = 0x145; // 10.0.2.13
    public const ushort SCAchievementCompletedPacket = 0x0AB; // 10.0.2.13
    public const ushort SCAchievementResetedPacket = 0x176; // 10.0.2.13
    public const ushort SCAchievementItemSentPacket = 0x10C; // 10.0.2.13
    public const ushort SCUpdatePremiumPointPacket = 0x086; // 10.0.2.13
    public const ushort SCPremiumPointChangedPacket = 0x12C; // 10.0.2.13
    public const ushort SCUnitGmModeChangedPacket = 0x140; // 10.0.2.13
    public const ushort SCUnitPvPPointsChangedPacket = 0xfff; // 10.0.2.13
    public const ushort SCRankAlarmPacket = 0x2CA; // 10.0.2.13
    public const ushort SCUnkPacket15 = 0x206; // Select Dimension, uint ZoneGroupId
    public const ushort SCUnkPacket16 = 0x207;
    public const ushort SCUnkPacket17 = 0x208; // Secure mode error message
    public const ushort SCUnkCharacterAddStatPacket = 0x209;
    public const ushort SCUnlockCurrencySlotPacket = 0x020;
    public const ushort SCUnkPacket20 = 0x20b;
    public const ushort SCUnkPacket21 = 0x20c;
    public const ushort SCUnkPacket22 = 0x20d;
    public const ushort SCUnkPacket23 = 0x20e;
    public const ushort SCUnkPacket24 = 0x20f;
    public const ushort SCUnkPacket28 = 0x210;
    public const ushort SCWorldMessagePacket = 0x238; // 10.0.2.13
    public const ushort SCUnkPacket25 = 0x212;
    public const ushort SCUnkPacket26 = 0x213;
    public const ushort SCUnkPacket27 = 0x214;
    public const ushort SCAccountAttributeListPacket = 0x29D;
    public const ushort SCAccountAttributeConfigPacket = 0x0A9;
    public const ushort SCIdleKickPacket = 0x03F; // 10.0.2.13
    public const ushort SCWorldRestrictOwnerChangePacket = 0x16A; // 10.0.2.13 SC_PACKET_WORLD_RESTRICT_OWNER_CHANGE (674)
    public const ushort SCLevelRestrictionConfigPacket = 0x353;
    public const ushort SCTaxItemConfigPacket = 0x343; // 10.0.2.13 SC_PACKET_TAX_ITEM_CONFIG (676)
    public const ushort SCInGameShopConfigPacket = 0x0E7; // 10.0.2.13 SC_PACKET_INGAME_SHOP_CONFIG (699)
    public const ushort SCGameRuleConfigPacket = 0x14D; // 10.0.2.13 SC_PACKET_GAME_RULE_CONFIG (700)
    public const ushort SCHousingAreaConfigPacket = 0x2BD; // 10.0.2.13 SC_PACKET_HOUSING_AREA_CONFIG (701)
    public const ushort SCSiegeZoneConfigPacket = 0x2BE; // 10.0.2.13 SC_PACKET_SIEGE_ZONE_CONFIG (702)
    public const ushort SCShowCurrentWorldPacket = 0x141; // 10.0.2.13 SC_PACKET_SHOW_CURRENT_WORLD (852)
    public const ushort SCWorldContentPacket = 0x009; // 10.0.2.13 SC_PACKET_WORLD_CONTENT (9)
    public const ushort SCServerFileTimeSyncPacket = 0x1B2; // 10.0.2.13 SC_PACKET_SERVER_FILE_TIME_SYNC (773)
    public const ushort SCRepreSentCharacterPacket = 0x29F; // 10.0.2.13 SC_PACKET_REPRESENT_CHARACTER (708)
    public const ushort SCAccountAttendancePacket = 0x31E; // 10.0.2.13 SC_PACKET_ACCOUNT_ATTENDANCE (713)
    public const ushort SCServerInfoPacket = 0x399; // 10.0.2.13 SC_PACKET_SERVER_INFO (921)
    public const ushort SCUnitOpenEquipInfoPacket = 0x26D;
    public const ushort SCSpawnedMonitorNpcsPacket = 0x001;
    public const ushort SCMonitorNpcSpawnedPacket = 0x2AF;
    public const ushort SCEventInfoCountPacket = 0x2DD; // 10.0.2.13 SC_PACKET_EVENT_INFO_COUNT (733)
    public const ushort SCFactionPowerScorePacket = 0x2AD; // 10.0.2.13 SC_PACKET_FACTION_POWER_SCORE (12)
    public const ushort SCIncreasedFavoritePortalLimitPacket = 0x32F; // 10.0.2.13 SC_PACKET_INCREASED_FAVORITE_PORTAL_LIMIT (141)
    public const ushort SCInstanceVisitCountsPacket = 0x274; // 10.0.2.13 SC_PACKET_INSTANCE_VISIT_COUNTS (492)
    public const ushort SCFavoriteCraftsPacket = 0x23A; // 10.0.2.13 SC_PACKET_FAVORITE_CRAFTS (570)
    public const ushort SCBattleFieldRecordsPacket = 0x2E5; // 10.0.2.13 SC_PACKET_BATTLE_FIELD_RECORDS (741)
    public const ushort SCCharacterPrivacyStatusUpdatePacket = 0x375; // 10.0.2.13 SC_PACKET_CHARACTER_PRIVACY_STATUS_UPDATE (885)
    public const ushort SCUpdateAdditionalSkillPointPacket = 0x381; // 10.0.2.13 SC_PACKET_UPDATE_ADDITIONAL_SKILL_POINT (897)
    public const ushort SCPlayerGameDataPacket = 0x39A; // 10.0.2.13 SC_PACKET_PLAYER_GAME_DATA (922)
    public const ushort SCCharacterPrelimEquipmentsPacket = 0x245; // 10.0.2.13 SC_PACKET_CHARACTER_PRELIM_EQUIPMENTS (121)
    public const ushort SCSystemFeatureStateListPacket = 0x393; // 10.0.2.13 SC_PACKET_SYSTEM_FEATURE_STATE_LIST (915)
    public const ushort SCWorldLevelInfoPacket = 0x38A; // 10.0.2.13 SC_PACKET_WORLD_LEVEL_INFO (906)

    // Ids for packet types the 10.0.2.13 client declares that this file did not. Recovered
    public const ushort SCAbilitySetSlotCountUpdatedPacket = 0x14B;
    public const ushort SCAbilitySetUpdatedPacket = 0x240;
    public const ushort SCAboxBlessUthstinApplyStatsPacket = 0x0DB;
    public const ushort SCAccountAttendanceAddedPacket = 0x2CA;
    public const ushort SCAccountAttendanceRewardedPacket = 0x2CC;
    public const ushort SCAccountAttributeRemovedPacket = 0x1C9;
    public const ushort SCUpdateSkillActiveTypePacket = 0x1F2;
    public const ushort SCListSkillActiveTypePacket = 0x2E1;
    public const ushort SCHeirSkillListPacket = 0x02D;
    public const ushort SCActivatedHeirSkillPacket = 0x18C;
    public const ushort SCResetHeirSkillPacket = 0x341;
    public const ushort SCHeirLevelUpPacket = 0x0AC;
    public const ushort SCAddContributionPointPacket = 0x27;
    public const ushort SCAppellationStampLifespanExpiredPacket = 0x383;
    public const ushort SCAppellationStampLifespanUpdatedPacket = 0x384;
    public const ushort SCArchePassChangeMissionPacket = 0x1D8;
    public const ushort SCArchePassMissionCountPacket = 0x1AC;
    public const ushort SCAttackFactionPacket = 0x082;
    public const ushort SCBalanceLevelChangedPacket = 0x069;
    public const ushort SCBattleFieldBestRatingRewardPacket = 0x2E7;
    public const ushort SCBlessUthstinApplyStatsPacket = 0x0A7;
    public const ushort SCBlessUthstinConsumeApplyStatsPacket = 0x23C;
    public const ushort SCBlessUthstinCopyPagePacket = 0x1AD;
    public const ushort SCBlessUthstinExpandPagePacket = 0x218;
    public const ushort SCBlessUthstinExtendMaxStatsPacket = 0x037;
    public const ushort SCBlessUthstinInitStatsPacket = 0x129;
    public const ushort SCBlessUthstinSelectPagePacket = 0x06D;
    public const ushort SCBlockInstanceNotifyPacket = 0x29B;
    public const ushort SCBlockItemSellFaileMessagePacket = 0x36F;
    public const ushort SCBossTelescopeToggledPacket = 0x226;
    public const ushort SCButlerDespawnedPacket = 0x349;
    public const ushort SCButlerLookChangedPacket = 0x2DC;
    public const ushort SCButlerSpawnedPacket = 0x347;
    public const ushort SCChangeAbilitySetPassiveBuffPacket = 0x0F2;
    public const ushort SCChangeSquadMemberRatingPacket = 0x126;
    public const ushort SCChargeSkillCooldownChangedPacket = 0x31D;
    public const ushort SCChronicleInfoDeletePacket = 0x15D;
    public const ushort SCChronicleInfoUpdatePacket = 0x2C8;
    public const ushort SCCompletedArchePassPacket = 0x2FD;
    public const ushort SCConnectStateMemberPacket = 0x246;
    public const ushort SCCraftOrderActionResultPacket = 0x2FC;
    public const ushort SCCraftOrderFeeInfoPacket = 0x31C;
    public const ushort SCDeclarationFailureReasonPacket = 0x055;
    public const ushort SCDelegateSquadLeaderPacket = 0x09E;
    public const ushort SCDeleteCraftOrderEntryPacket = 0x1E4;
    public const ushort SCDeleteExpeditionPortalPacket = 0x372;
    public const ushort SCDominionNonPvPStartedPacket = 0x2B1;
    public const ushort SCDominionNonPvPStoppedPacket = 0x21B;
    public const ushort SCDominionTaxChangedPacket = 0x172;
    public const ushort SCDoodadFirstInteractionSyncPacket = 0x2CD;
    public const ushort SCDoodadHitPacket = 0x19F;
    public const ushort SCDoodadInteractionCallbackPacket = 0x2EE;
    public const ushort SCSetDoodadManikinSkinPacket = 0x334; // 10.0.2.13
    public const ushort SCDoodadMapIconRemovedPacket = 0x322;
    public const ushort SCDoodadWorldmapTextAddedPacket = 0x324;
    public const ushort SCDoodadWorldmapTextRemovedPacket = 0x325;
    public const ushort SCDropQuestsByFactionChangePacket = 0x222;
    public const ushort SCDumpGachaRecordPacket = 0x2E4;
    public const ushort SCElectSiegeRaidOwnerPacket = 0x32F;
    public const ushort SCEnsembleMidiBinReadyPacket = 0x25F;
    public const ushort SCExpdWarHistoriesPacket = 0x0D7;
    public const ushort SCExpeditionApplicantAcceptPacket = 0x1E6;
    public const ushort SCExpeditionApplicantAddPacket = 0x368;
    public const ushort SCExpeditionApplicantDelPacket = 0x44;
    public const ushort SCExpeditionApplicantRejectPacket = 0x0B4;
    public const ushort SCExpeditionBuffChangedPacket = 0x4E;
    public const ushort SCExpeditionCreatedPacket = 0x371;
    public const ushort SCExpeditionExpAddPacket = 0x4C;
    public const ushort SCExpeditionMemberListEndPacket = 0x295;
    public const ushort SCExpeditionPortalTimerPacket = 0x373;
    public const ushort SCExpeditionRejoinFailPacket = 0x310;
    public const ushort SCExpeditionShopHistoriesPacket = 0x31;
    public const ushort SCExpeditionSummonSuggestPacket = 0x18D;
    public const ushort SCExpeditionWarStatePacket = 0x216;
    public const ushort SCFactionCompetitionUpdatePointPacket = 0x212;
    public const ushort SCFactionImmigrateLimitDataPacket = 0x51;
    public const ushort SCFactionMobilizationOrderPacket = 0x2E3;
    public const ushort SCFactionRelationRequestPacket = 0x2B;
    public const ushort SCFactionRelationResponsePacket = 0x2C;
    public const ushort SCFamilyChangeMemberLevelPacket = 0x5E;
    public const ushort SCFamilyChangeMemberRolePacket = 0x5D;
    public const ushort SCFamilyExpChangeDryNotifyPacket = 0x61;
    public const ushort SCFamilyExpChangeNotifyPacket = 0x131;
    public const ushort SCFamilyInfoSetPacket = 0x10B;
    public const ushort SCFestivalZoneStatePacket = 0x09A;
    public const ushort SCFollowAskPacket = 0x208;
    public const ushort SCFollowRespPacket = 0x09B;
    public const ushort SCFriendRequestPacket = 0x379;
    public const ushort SCFriendAcceptPacket = 0x37A;
    public const ushort SCFriendCancelPacket = 0x37B;
    public const ushort SCGamePointInitedPacket = 0x23D;
    public const ushort SCGameScheduleControlPacket = 0x276;
    public const ushort SCGmDumpItemGradeEnchantRatioPacket = 0x1F5;
    public const ushort SCGmDumpSkillsPacket = 0x1FD;
    public const ushort SCGmUseWithTargetPacket = 0x20C;
    public const ushort SCHGRequestPacket = 0x321;
    public const ushort SCHeroBindFactionRezDistrictInfoPacket = 0x04E;
    public const ushort SCHeroCandidateNotificationPacket = 0x08B;
    public const ushort SCHeroDominionPointCountPacket = 0x19B;
    public const ushort SCHeroElectionMailPacket = 0x2B1;
    public const ushort SCHeroGiveDominionPointPacket = 0x2B6;
    public const ushort SCHeroInfoDeletedPacket = 0x130;
    public const ushort SCHeroScoreUpdatedPacket = 0x164;
    public const ushort SCHeroSeasonInfoPacket = 0x04A;
    public const ushort SCHeroSeasonOffPacket = 0x2BE;
    public const ushort SCHeroVotingPacket = 0x322;
    public const ushort SCHouseRotatedPacket = 0x0E0;
    public const ushort SCHousingDecoLimitExpandedPacket = 0x067;
    public const ushort SCIgnoreMinimumGameSizeNotifyPacket = 0x20E;
    public const ushort SCIndunDirectTelPacket = 0x333;
    public const ushort SCIndunInitialRoundInfoPacket = 0x204;
    public const ushort SCIndunPortalSpawnPacket = 0x29C;
    public const ushort SCIndunRoundPlayStatusPacket = 0x31A;
    public const ushort SCInstantGameCountDownPacket = 0x15B;
    public const ushort SCInstantGameKillstreakResetPacket = 0x342;
    public const ushort SCInstantGameReentryNotifyPacket = 0x0B3;
    public const ushort SCInstantGameStartPointReturnTimePacket = 0x2C1;
    public const ushort SCInstantGameUnearnedWinPacket = 0x0D2;
    public const ushort SCInstantGameUpdateTimePacket = 0x015;
    public const ushort SCInstantTimePacket = 0x2E8;
    public const ushort SCIntegrationDummyFactionPacket = 0x352;
    public const ushort SCInvitationAnswerPacket = 0x256;
    public const ushort SCItemElementResultPacket = 0x365;
    public const ushort SCItemEnchantMagicalResultPacket = 0xCB;
    public const ushort SCItemSmeltingResultPacket = 0x064;
    public const ushort SCItemSocketingResultPacket = 0xCA;
    public const ushort SCLoadCraftOrderEntryPacket = 0x278;
    public const ushort SCMailRemovedFromAboxPacket = 0x0DD;
    public const ushort SCMatchingInvitationInfoPacket = 0x065;
    public const ushort SCMateEquipmentFlagsChangedPacket = 0x0E6;
    public const ushort SCNewDayStartPacket = 0x2CB;
    public const ushort SCNotifySquadEventPacket = 0x19E;
    public const ushort SCNuonsArrowMsgPacket = 0x255;
    public const ushort SCPassportIssuedPacket = 0x2F8;
    public const ushort SCPirateMemberLimitCountPacket = 0x36D;
    public const ushort SCPlotAuctionBidResponsePacket = 0x395;
    public const ushort SCPlotAuctionBidUpdatePacket = 0x397;
    public const ushort SCPremiumBonusListPacket = 0x168;
    public const ushort SCProtectSensitiveOperationResultPacket = 0x28E;
    public const ushort SCUpdatedSlaveSourceItemPacket = 0x296;
    public const ushort SCQuestAcceptConditionalPacket = 0x18F;
    public const ushort SCQuestNotifierInitPacket = 0x287;
    public const ushort SCRaidApplicantAcceptPacket = 0x301;
    public const ushort SCRaidApplicantDelPacket = 0x300;
    public const ushort SCRaidApplicantRejectPacket = 0x302;
    public const ushort SCRaidRecruitDelPacket = 0x2FB;
    public const ushort SCRaidRecruitDetailPacket = 0x2FE;
    public const ushort SCRaidRecruitOptionPacket = 0x2FD;
    public const ushort SCRandomShopBaseInfoUpdatePacket = 0x36B;
    public const ushort SCRandomShopInfoResetPacket = 0x0CD;
    public const ushort SCReopenRandomBoxRemovePacket = 0x388;
    public const ushort SCReportBadwordUserPacket = 0x2D0;
    public const ushort SCReputationChangedPacket = 0x058;
    public const ushort SCUpdateMerchantGoodLimitPurchasePacket = 0x376;
    public const ushort SCBuyFailedMerchantGoodLimitPurchasePacket = 0x377;
    public const ushort SCResetMerchantGoodLimitPurchasePacket = 0x378;
    public const ushort SCResidentBalanceInfoPacket = 0x1F9;
    public const ushort SCResidentInfoPacket = 0x26C;
    public const ushort SCReturnAccountStatusPacket = 0x155;
    public const ushort SCRotateHousePacket = 0x9A;
    public const ushort SCSailingActivityEnterResponsePacket = 0x390;
    public const ushort SCSailingActivityErrorPacket = 0x38F;
    public const ushort SCSailingActivityPointsChangedPacket = 0x392;
    public const ushort SCSecondPassReservedClearTimePacket = 0x0DF;
    public const ushort SCSelectedInstanceDifficultPacket = 0x2DC;
    public const ushort SCSetExpeditionProtectDatePacket = 0x063;
    public const ushort SCSiegeScorePointPacket = 0x242;
    public const ushort SCSkillCooldownReducePacket = 0x038;
    public const ushort SCSlaveEquipmentExpiredPacket = 0x2C7;
    public const ushort SCSlaveEquipmentFlagsChangedPacket = 0x1B8;
    public const ushort SCSnowingEverywherePacket = 0x09D;
    public const ushort SCSquadSetGameInfoPacket = 0x2A6;
    public const ushort SCStoreTradeFailedPacket = 0x016;
    public const ushort SCSuspectGoingBotTrialPacket = 0x22C;
    public const ushort SCSysIndunIndexPacket = 0x31F;
    public const ushort SCTeamJointBreakPacket = 0x02A;
    public const ushort SCTeamOfficerChangedPacket = 0x171;
    public const ushort SCTeamSummonSuggestPacket = 0x221;
    public const ushort SCTodayAssignmentChangedPacket = 0x091;
    public const ushort SCTodayAssignmentGoalPacket = 0x286;
    public const ushort SCTodayAssignmentItemSentPacket = 0x2C5;
    public const ushort SCTodayAssignmentResetCountPacket = 0x16C;
    public const ushort SCUlcNeedSquadNoticePacket = 0x025;
    public const ushort SCUnitCollisionResultPacket = 0x18A;
    public const ushort SCUnlockLearnSkillPacket = 0x146;
    public const ushort SCUpdateHousingUccPacket = 0x209;
    public const ushort SCUpdatedFavoriteCraftsPacket = 0x23B;
    public const ushort SCZoneScoreResetPacket = 0x1BB;
    public const ushort SCZoneScoreUpdatePacket = 0x26E;
    public const ushort SCRankSnapshotPacket = 0x39B;
    public const ushort SCRankRewardSnapshotPacket = 0x27B;
    public const ushort SCGmDumpAchievementPacket = 0x25D;
    public const ushort SCGmDumpAppellationPacket = 0x266;
    public const ushort SCGmDumpBuycodePacket = 0x08A;
    public const ushort SCGmDumpDailyResetPacket = 0x201;
    public const ushort SCGmDumpGamePointPacket = 0x1FA;
    public const ushort SCGmDumpGuidActionSlotPacket = 0x202;
    public const ushort SCGmDumpRecordPacket = 0x161;
    public const ushort SCGmDumpRestrictPacket = 0x1FC;
    public const ushort SCGmDumpReturnDistrictPacket = 0x13F;
    public const ushort SCGmDumpSubStatPacket = 0x250;
    public const ushort SCGmServerAttributeValuePacket = 0x366;

    public const ushort SCCombatResourcePointPacket = 0x35B;

    public const ushort SCSkillMapEffectPacket = 0x32B;

    public const ushort SCAccountAttributeUpdatedPacket = 0x29E;
    // Present in the modern backend but not mapped in AA8 r558734.
    public const ushort SCAddFriendPacket = 0xFFF;
    public const ushort SCAggroTargetChanged = 0xFFF;
    public const ushort SCChangeJuryOkCountPacket = 0xFFF;
    public const ushort SCCountUnreadMailPacket = 0xFFF;
    public const ushort SCFactionListPacket = 0xFFF;
    public const ushort SCMyHousePacket = 0xFFF;
    public const ushort SCMyHouseRemovedPacket = 0xFFF;
    public const ushort SCRefreshInCharacterListPacket = 0xFFF;
    public const ushort SCTrialCanceledPacket = 0xFFF;
}